apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-recommendations-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-recommendations-app
  template:
    metadata:
      labels:
        app: hotel-recommendations-app
    spec:
      containers:
        - name: hotel-recommendations-app
          image: hotel-recommendations-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: FLASK_ENV
              value: "production"

---
apiVersion: v1
kind: Service
metadata:
  name: hotel-recommendations-service
spec:
  selector:
    app: hotel-recommendations-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer